/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const gamestate_get_current_time: (a: number) => number;
export const gamestate_get_lap: (a: number) => number;
export const gamestate_get_rotation_y: (a: number) => number;
export const gamestate_get_sim_node_positions: (a: number) => any;
export const gamestate_get_speed: (a: number) => number;
export const gamestate_get_x: (a: number) => number;
export const gamestate_get_y: (a: number) => number;
export const gamestate_get_z: (a: number) => number;
export const gamestate_init_simulation: (a: number, b: number, c: number) => void;
export const gamestate_is_completed: (a: number) => number;
export const gamestate_load_policy: (a: number, b: number, c: number, d: number, e: number) => void;
export const gamestate_new_wasm: (a: number, b: number) => number;
export const gamestate_start_race: (a: number, b: number) => void;
export const gamestate_update: (a: number, b: number, c: number, d: number, e: number) => void;
export const __wbg_gamestate_free: (a: number, b: number) => void;
export const __wbg_get_gamestate_current_time: (a: number) => number;
export const __wbg_get_gamestate_lap: (a: number) => number;
export const __wbg_get_gamestate_last_angle: (a: number) => number;
export const __wbg_get_gamestate_race_completed: (a: number) => number;
export const __wbg_get_gamestate_race_started: (a: number) => number;
export const __wbg_get_gamestate_rotation_y: (a: number) => number;
export const __wbg_get_gamestate_speed: (a: number) => number;
export const __wbg_get_gamestate_start_time: (a: number) => number;
export const __wbg_get_gamestate_total_angle: (a: number) => number;
export const __wbg_get_gamestate_total_laps: (a: number) => number;
export const __wbg_get_gamestate_x: (a: number) => number;
export const __wbg_get_gamestate_y: (a: number) => number;
export const __wbg_get_gamestate_z: (a: number) => number;
export const __wbg_set_gamestate_current_time: (a: number, b: number) => void;
export const __wbg_set_gamestate_lap: (a: number, b: number) => void;
export const __wbg_set_gamestate_last_angle: (a: number, b: number) => void;
export const __wbg_set_gamestate_race_completed: (a: number, b: number) => void;
export const __wbg_set_gamestate_race_started: (a: number, b: number) => void;
export const __wbg_set_gamestate_rotation_y: (a: number, b: number) => void;
export const __wbg_set_gamestate_speed: (a: number, b: number) => void;
export const __wbg_set_gamestate_start_time: (a: number, b: number) => void;
export const __wbg_set_gamestate_total_angle: (a: number, b: number) => void;
export const __wbg_set_gamestate_total_laps: (a: number, b: number) => void;
export const __wbg_set_gamestate_x: (a: number, b: number) => void;
export const __wbg_set_gamestate_y: (a: number, b: number) => void;
export const __wbg_set_gamestate_z: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
